language: php
php:
  - "7.0"
  - "5.6"

before_script:
  - cp .env.travis .env
  - mysql -e 'create database `simple-quiz`;'
  - composer self-update
  - composer install --no-interaction
  - chmod -R 777 storage
script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - vendor/bin/phpunit

matrix:
  - fast_finish: true